version: 0.2
env:
  variables:
    S3_BUCKET_NAME: "a087013-frontend-website"

cache:
  paths:
    - node_modules/*/

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3 bucket: $S3_BUCKET_NAME"
      - ls -al
      - ls -al dist
      - aws s3 sync dist s3://$S3_BUCKET_NAME --delete

artifacts:
  files:
    - '**/*'